-- ============================================================
-- StreetIQ - Database Setup
-- Creates the required empty PostgreSQL tables
-- ============================================================


-- ============================================================
-- 1. ROUTES
-- ============================================================

CREATE TABLE IF NOT EXISTS routes (
    route_id VARCHAR(20) PRIMARY KEY,
    route_number VARCHAR(50),
    route_name VARCHAR(150),
    start_point TEXT,
    end_point TEXT
);


-- ============================================================
-- 2. BUSES
-- ============================================================

CREATE TABLE IF NOT EXISTS buses (
    bus_id VARCHAR(20) PRIMARY KEY,
    registration_number VARCHAR(50),
    operator VARCHAR(100),
    status VARCHAR(50)
);


-- ============================================================
-- 3. ROAD SEGMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS road_segments (
    segment_id VARCHAR(20) PRIMARY KEY,
    road_name VARCHAR(200),

    start_latitude DOUBLE PRECISION,
    start_longitude DOUBLE PRECISION,

    end_latitude DOUBLE PRECISION,
    end_longitude DOUBLE PRECISION,

    segment_length_m DOUBLE PRECISION,

    road_condition JSONB DEFAULT '{}'::JSONB
);


-- ============================================================
-- 4. OBSERVATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS observations (
    observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    bus_id VARCHAR(20) NOT NULL,
    segment_id VARCHAR(20) NOT NULL,

    observed_at TIMESTAMPTZ,

    road_condition JSONB DEFAULT '{}'::JSONB,

    route_id VARCHAR(20),

    CONSTRAINT fk_observations_bus
        FOREIGN KEY (bus_id)
        REFERENCES buses(bus_id),

    CONSTRAINT fk_observations_segment
        FOREIGN KEY (segment_id)
        REFERENCES road_segments(segment_id),

    CONSTRAINT fk_observations_route
        FOREIGN KEY (route_id)
        REFERENCES routes(route_id)
);